% STAMP regression tests for Scapy

# More information at http://www.secdev.org/projects/UTscapy/

############
# STAMP
############

+ STAMP tests

= Load module

load_layer("stamp")

= Test STAMP Session-Sender Test (Unauthenticated)
~ stamp-session-sender-test

created = STAMPSessionSenderTestUnauthenticated(
    seq=0x1234,
    ts=NTPTimestamp(seconds=1234, fraction=5678),
    err_estimate=ErrorEstimate(
        S=1,
        Z=0,
        scale=0x12,
        multiplier=0x34
    ),
    ssid=1357
)
assert raw(created) == b'\x00\x00\x12\x34\x00\x00\x04\xD2\x00\x00\x16\x2E\x92\x34\x05\x4D\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
parsed = STAMPSessionSenderTestUnauthenticated(raw(created))
assert parsed.seq == 0x1234
assert parsed.ts.seconds == 1234
assert parsed.ts.fraction == 5678
assert parsed.err_estimate.S == 1
assert parsed.err_estimate.Z == 0
assert parsed.err_estimate.scale == 0x12
assert parsed.err_estimate.multiplier == 0x34
assert parsed.ssid == 1357
assert parsed.mbz == 0
assert not parsed.tlv_objects


= Test STAMP Session-Reflector Test (Unauthenticated)
~ stamp-session-reflector-test

created = STAMPSessionReflectorTestUnauthenticated(
    seq=0x1234,
    ts=NTPTimestamp(seconds=1234, fraction=5678),
    err_estimate=ErrorEstimate(
        S=1,
        Z=0,
        scale=0x12,
        multiplier=0x34
    ),
    ssid=1357,
    ts_rx=NTPTimestamp(seconds=4321, fraction=8765),
    seq_sender=0x4321,
    ts_sender=NTPTimestamp(seconds=2143, fraction=6587),
    err_estimate_sender=ErrorEstimate(
        S=0,
        Z=0,
        scale=0x21,
        multiplier=0x43
    ),
    ttl_sender=111
)
assert raw(created) == b'\x00\x00\x12\x34\x00\x00\x04\xD2\x00\x00\x16\x2E\x92\x34\x05\x4D\x00\x00\x10\xE1\x00\x00\x22\x3D\x00\x00\x43\x21\x00\x00\x08\x5F\x00\x00\x19\xBB\x21\x43\x00\x00\x6F\x00\x00\x00'
parsed = STAMPSessionReflectorTestUnauthenticated(raw(created))
assert parsed.seq == 0x1234
assert parsed.ts.seconds == 1234
assert parsed.ts.fraction == 5678
assert parsed.err_estimate.S == 1
assert parsed.err_estimate.Z == 0
assert parsed.err_estimate.scale == 0x12
assert parsed.err_estimate.multiplier == 0x34
assert parsed.ssid == 1357
assert parsed.ts_rx.seconds == 4321
assert parsed.ts_rx.fraction == 8765
assert parsed.seq_sender == 0x4321
assert parsed.ts_sender.seconds == 2143
assert parsed.ts_sender.fraction == 6587
assert parsed.err_estimate_sender.S == 0
assert parsed.err_estimate_sender.Z == 0
assert parsed.err_estimate_sender.scale == 0x21
assert parsed.err_estimate_sender.multiplier == 0x43
assert parsed.mbz1 == 0
assert parsed.ttl_sender == 111
assert parsed.mbz2 == 0
assert not parsed.tlv_objects

